name: Release

on:
  push:
    tags:
      - "[0-9]+.*"

jobs:
  release:
    if: >-
      github.repository == 'haithanh456/Codes' &&
      !github.event.repository.fork
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build package
        run: python -m build

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: v${{ github.ref_name }}
          files: dist/*
          generate_release_notes: true
