name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    if: github.repository == 'haithanh456/Codes'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build package
        run: python -m build

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true